# Generated by Django 5.0.6 on 2024-07-13 14:22

import custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=custom_storages.MediaStorage(), upload_to='profile_pics'),
        ),
    ]
